version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./Database/Migrations/Init_Db.sql:/docker-entrypoint-initdb.d/Init_Db.sql
      - ./Database/Functions/CreateUser.sql:/docker-entrypoint-initdb.d/CreateUser.sql
      - ./Database/Functions/DeleteUser.sql:/docker-entrypoint-initdb.d/DeleteUser.sql
      - ./Database/Functions/GetAllUsers.sql:/docker-entrypoint-initdb.d/GetAllUsers.sql
      - ./Database/Functions/GetUserById.sql:/docker-entrypoint-initdb.d/GetUserById.sql
      - ./Database/Functions/UpdateUser.sql:/docker-entrypoint-initdb.d/UpdateUser.sql
      - ./Database/Functions/GetUserByName.sql:/docker-entrypoint-initdb.d/GetUserByName.sql
      - ./Database/Functions/GetUserBySurname.sql:/docker-entrypoint-initdb.d/GetUserBySurname.sql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper