version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./Database/Migrations/Init_Db.sql:/docker-entrypoint-initdb.d/Init_Db.sql
      - ./Database/Functions/CreateUser.sql:/docker-entrypoint-initdb.d/CreateUser.sql